micronaut:
  application:
    name: CRUD
  server:
    port: 56641
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne